import { Ban, ChevronRight, Copy, Lock, LogOut, Play, RotateCcw, Unlock, UserMinus, Users } from 'lucide-react'
import { QRCodeSVG } from 'qrcode.react'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { Link, Navigate, useParams } from 'react-router-dom'
import { Brand, SoundToggle } from '../components/Layout'
import { AnswerGrid, ConnectionBadge, ErrorBanner, Leaderboard, Loading, PhaseTimer, QuestionMedia } from '../components/ui'
import { getGameState, heartbeat, hostAction, removePlayer, watchGame } from '../lib/api'
import { playCue } from '../lib/sound'
import { useHost } from '../lib/useHost'
import type { GameState } from '../lib/types'

export function HostGamePage() {
  const { sessionId = '' } = useParams(); const { user, loading: authLoading } = useHost()
  const [state, setState] = useState<GameState | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const [connected, setConnected] = useState(true); const [muted, setMutedState] = useState(() => localStorage.getItem('toohak-muted') === 'true')
  const previousPhase = useRef('')
  const load = useCallback(async () => { try { setState(await getGameState(sessionId)); setConnected(true); setError('') } catch (caught) { setConnected(false); setError(caught instanceof Error ? caught.message : 'Connection lost.') } }, [sessionId])
  useEffect(() => { if (!user) return; void load(); const stop = watchGame(sessionId, () => void load()); const poll = setInterval(() => void load(), 2000); const beat = setInterval(() => void heartbeat(sessionId).catch(() => setConnected(false)), 15000); return () => { stop(); clearInterval(poll); clearInterval(beat) } }, [sessionId, user, load])
  useEffect(() => { if (state && previousPhase.current && previousPhase.current !== state.phase) playCue(state.phase === 'final' ? 'win' : state.phase === 'reveal' ? 'reveal' : 'tick', muted); if (state) previousPhase.current = state.phase }, [state?.phase, muted])
  function setMuted(value: boolean) { localStorage.setItem('toohak-muted', String(value)); setMutedState(value) }
  const joinUrl = useMemo(() => state ? `${location.origin}${location.pathname}#/?pin=${state.pin}` : '', [state])
  async function action(name: string) { setBusy(true); setError(''); try { await hostAction(sessionId, name); await load() } catch (caught) { setError(caught instanceof Error ? caught.message : 'Action failed.') } finally { setBusy(false) } }
  if (authLoading) return <Loading />
  if (!user) return <Navigate to="/auth" replace />
  if (!state) return <div className="game-loading">{error ? <ErrorBanner message={error} onRetry={load} /> : <Loading label="Connecting to the room…" />}</div>

  return <div className="game-shell host-game">
    <header className="game-topbar"><Brand compact /><div className="game-progress"><span>{state.quizTitle}</span>{state.phase !== 'lobby' && <strong>{Math.min(state.currentQuestionIndex + 1, state.totalQuestions)} / {state.totalQuestions}</strong>}</div><ConnectionBadge connected={connected} /><SoundToggle muted={muted} setMuted={setMuted} /><Link className="icon-button surface" to="/dashboard" aria-label="Exit to dashboard"><LogOut /></Link></header>
    {error && <div className="floating-error"><ErrorBanner message={error} /></div>}
    {state.phase === 'lobby' ? <main className="lobby-layout"><section className="pin-board"><span className="overline">JOIN AT THIS LINK</span><p>{location.host}{location.pathname}#/</p><h1>{state.pin.slice(0, 3)} <span>{state.pin.slice(3)}</span></h1><div className="lobby-actions"><button className="button button-light" onClick={() => navigator.clipboard.writeText(joinUrl)}><Copy /> Copy join link</button><button className="button button-light" onClick={() => action(state.locked ? 'unlock' : 'lock')}>{state.locked ? <><Unlock /> Unlock joining</> : <><Lock /> Lock joining</>}</button></div><QRCodeSVG value={joinUrl} size={164} bgColor="#ffffff" fgColor="#3b0b1b" level="M" marginSize={2} /></section><section className="player-board"><div className="player-board-heading"><div><span className="eyebrow">LIVE LOBBY</span><h2><Users /> {state.players.length} player{state.players.length === 1 ? '' : 's'} joined</h2></div><button className="button button-primary button-large" onClick={() => action('start')} disabled={busy || !state.players.length}><Play /> Start game</button></div><div className="player-cloud">{state.players.map((player) => <span key={player.id}>{player.nickname}<button aria-label={`Remove ${player.nickname}`} onClick={() => void removePlayer(sessionId, player.id).then(load)}><UserMinus /></button></span>)}</div>{!state.players.length && <div className="lobby-empty"><Users /><p>Players will appear here as they join.</p></div>}</section></main>
      : state.phase === 'countdown' ? <main className="countdown-stage"><span>GET READY</span><PhaseTimer endsAt={state.phaseEndsAt} /><h2>Question {state.currentQuestionIndex + 1} of {state.totalQuestions}</h2></main>
      : state.phase === 'question_open' && state.question ? <main className="game-stage"><div className="question-kicker"><span>QUESTION {state.currentQuestionIndex + 1}</span><span>{state.submittedCount} / {state.players.length} answered</span></div><div className="stage-question"><PhaseTimer endsAt={state.phaseEndsAt} /><h1>{state.question.prompt}</h1></div><QuestionMedia path={state.question.imagePath} /><AnswerGrid question={state.question} value={null} disabled onChange={() => undefined} /><div className="host-controls"><button className="button button-dark" disabled={busy} onClick={() => action('reveal')}>Close answers & reveal <ChevronRight /></button></div></main>
      : state.phase === 'reveal' && state.question ? <main className="game-stage reveal-stage"><div className="question-kicker"><span>ANSWER REVEAL</span><span>{state.submittedCount} responses</span></div><h1>{state.question.prompt}</h1><QuestionMedia path={state.question.imagePath} /><AnswerGrid question={state.question} value={null} disabled correctIds={state.reveal?.correctOptionIds} onChange={() => undefined} />{state.question.kind === 'typed' && <div className="accepted-answer"><strong>Accepted:</strong> {state.reveal?.acceptedAnswers.join(' · ')}</div>}{state.reveal?.explanation && <div className="explanation"><strong>Good to know</strong><p>{state.reveal.explanation}</p></div>}<div className="distribution">{Object.entries(state.reveal?.distribution ?? {}).map(([key, count]) => <span key={key}>{key}: <strong>{count}</strong></span>)}</div><div className="host-controls"><button className="button button-dark" onClick={() => action('leaderboard')}>Show leaderboard <ChevronRight /></button></div></main>
      : state.phase === 'leaderboard' ? <main className="leaderboard-stage"><span className="eyebrow">AFTER {state.currentQuestionIndex + 1} QUESTIONS</span><h1>Who’s leading?</h1><Leaderboard players={state.leaderboard} /><button className="button button-light button-large" onClick={() => action(state.currentQuestionIndex + 1 >= state.totalQuestions ? 'finish' : 'next')}>{state.currentQuestionIndex + 1 >= state.totalQuestions ? 'Final podium' : 'Next question'} <ChevronRight /></button></main>
      : state.phase === 'final' || state.phase === 'ended' ? <main className="final-stage"><span className="eyebrow">FINAL RESULTS</span><h1>What a finish!</h1><Leaderboard players={state.leaderboard} podium /><div className="button-row"><Link className="button button-light" to={`/reports/session/${sessionId}`}>View full report</Link><button className="button button-light" onClick={() => action('replay')}><RotateCcw /> Replay</button><button className="button button-dark" onClick={() => action('end')}><Ban /> End room</button></div></main> : null}
  </div>
}
